### ISSUE TITLE
Investigate the need for .gitignore for a repo

### ISSUE THREAD

**Issue by sagarVL** [sagarVL/TUHH_ISM_tumor_detection#2]
Every repo on Git has a .gitignore file. It would be nice if you find out what that is and why it is required.

**Comment by sagarVL** [comment]
@SubramanyaGurumurthy keep a deadline,i.e., Saturday

**Comment by SubramanyaGurumurthy** [comment]
subramanya.nanjangud@tuhh.de is inviting you to a scheduled Zoom meeting.

Topic: ISM first meeting
Time: Nov 21, 2020 03:00 PM Amsterdam, Berlin, Rome, Stockholm, Vienna

Join Zoom Meeting
https://tuhh.zoom.us/j/86314860425?pwd=SFBveVczaEdPM29XVWc5TXpDUGxWZz09

Meeting ID: 863 1486 0425
Passcode: 191090
One tap mobile
+496971049922,,86314860425#,,,,,,0#,,191090# Germany
+493056795800,,86314860425#,,,,,,0#,,191090# Germany

Dial by your location
        +49 69 7104 9922 Germany
        +49 30 5679 5800 Germany
        +49 69 3807 9883 Germany
        +49 695 050 2596 Germany
Meeting ID: 863 1486 0425
Passcode: 191090
Find your local number: https://tuhh.zoom.us/u/kcZHNDERpq

Join by Skype for Business
https://tuhh.zoom.us/skype/86314860425

**Comment by sagarVL** [comment]
@SubramanyaGurumurthy the comments in the issue should be regarding the issue and not any scheduled appointments.

**Comment by SubramanyaGurumurthy** [comment]
@sagarVL Oh okay !!

**Comment by SubramanyaGurumurthy** [comment]
gitignore - Specifies intentionally untracked files to ignore

For more details on this plz visit this page: https://git-scm.com/docs/gitignore

**Comment by sagarVL** [comment]
@SubramanyaGurumurthy thanks for the research! It would be nice if you can add this file to the repo after the phase 1 code has been submitted. I will reopen this issue. Link the PR which will contain the .gitignore file you add. This issue will automatically close once the PR has been approved! :)
